#!/bin/bash
echo "This is a sample math program"
echo "We are going to perform some basic arithematic operations"
echo "enter the first value"
read x
echo "enter the second value"
read y
sum=$($x+$y)
echo "the sum of two numbers is"
echo $sum
